# This is a basic workflow to help you get started with Actions

name: plan_and_deploy_unit_tests_dev

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  plan_and_deploy_unit_tests_dev:
    # The type of runner that the job will run on
    #runs-on: ['atmos-aws-arc-runner-set']
    runs-on: ['eccs-devops-atmos-actions-runner-dev-01']
    container:
        #image: alpine:latest
        image: sanofi-docker-atmos-local.jfrog.io/furno_devops_v03:latest
        credentials:
        # the artifactory user name is the complete email address of the user in lowercase, example: gitlab-automation@sanofi.com
          username: ${{ secrets.DOCKER_USER}}
        # the artifactory token is obtained from the artifactory user's profile page and is used as-is (ie. no base64 encoding)
          password: ${{ secrets.DOCKER_TOKEN}}
    env:
      PLAN: 'create.plan'
      DESTROYPLAN: 'destroy.plan'
      TF_VAR_ADMINKEY: ${{ secrets.TF_VAR_ADMINKEY}}
      TF_VAR_IAM_ENTITYID: ${{ secrets.IAM_ENTITY}}
      TF_VAR_IAM_WILDCARDENTITYID: ${{ secrets.IAM_WILDCARDENTITYID }}
      AWS_WEB_IDENTITY_TOKEN_FILE: ${{ secrets.SHARED_GHRUNNER_AWS_WEB_IDENTITY_TOKEN_FILE }}
      AWS_ROLE_ARN: ${{ secrets.SHARED_GHRUNNER_AWS_ROLE_ARN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Assume the aws role and set up the credentials for awscli/terraform
      - name: assume role and run terraform plan
        run: |
          chmod +x ./assume_role.sh
          . ./assume_role.sh "nfurno-devops-test" "CE_AppAdminRunner"
          cd unit_test_role_deployment
          cp vars/variables-devops-dev-aws.tf variables-devops-dev-dev.tf
          ls -la
          terraform version
          terraform init -backend-config="backend/backend-devops-dev-aws.tf"
          terraform validate
          terraform plan -destroy -out $DESTROYPLAN
          terraform apply -auto-approve $DESTROYPLAN
          terraform plan -out $PLAN 
          terraform apply -auto-approve $PLAN